import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Providers from "@/provider/tanstack";
import DoYouKnow from "@/components/DoYouKnow";
import localFont from "next/font/local";
import { Noto_Serif_Devanagari } from "next/font/google";
const abhinav = localFont({
  src: "../public/fonts/Abhinav.ttf", // Path relative to this file
  variable: "--font-abhinav",
});
const devanagari = Noto_Serif_Devanagari({
  weight: "400",
  subsets: ["devanagari"],
  variable: "--font-devanagari",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${abhinav.variable} ${devanagari.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <Providers>
          {children}
          <DoYouKnow />
        </Providers>
      </body>
    </html>
  );
}
