import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/components/QueryProvider";
import {Plus_Jakarta_Sans} from "next/font/google"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const PlusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap",
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={PlusJakartaSans.className}>
      <body
      className={`${geistSans.variable} ${PlusJakartaSans.variable} ${geistMono.variable}`}
      >
        <QueryProvider>
           {children}
        </QueryProvider>
      </body>
    </html>
  );
}
